### ISSUE TITLE
Notification Update Issue

### ISSUE THREAD

**Issue by bluke90** [bluke90/TaskIt_7.0#1]
App throws Fatal Unhandled Exception due to a foreign key issue when attempting to reschedule notification after editing on EditTaskPage. See error below:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: The property 'Notification.Id' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key, first delete the dependent and invoke 'SaveChanges', and then associate the dependent with the new principal.
[mono-rt]    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetPropertyModified(IProperty property, Boolean changeState, Boolean isModified, Boolean isConceptualNull, Boolean acceptChanges)
[mono-rt]    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectValueChange(InternalEntityEntry entry, IProperty property)
[mono-rt]    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
[mono-rt]    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
[mono-rt]    at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
[mono-rt]    at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
[mono-rt]    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
[mono-rt]    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
[mono-rt]    at TaskIt.EditTaskPage.doneClicked(Object sender, EventArgs e) in C:\Users\****\******\******\Repos\TaskIt\TaskIt\EditTaskPage.xaml.cs:line 91
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

**Comment by bluke90** [comment]
Instead of using UserTask.Notification.Id I am now using a list of IDs to accommodate multiple scheduled notifications. this also resolved the foreign key issue.
